# Generated by Django 3.2.13 on 2022-06-02 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planning',
            old_name='semestre',
            new_name='semester',
        ),
    ]
