# Generated by Django 3.2.13 on 2022-05-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='abr',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='abr',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
