# Generated by Django 3.2.13 on 2022-06-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_grade_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provide',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='provide',
            name='start_time',
        ),
        migrations.AddField(
            model_name='provide',
            name='range',
            field=models.CharField(choices=[('hour1', 'hour1'), ('hour2', 'hour2')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='planning',
            name='school_year',
            field=models.CharField(choices=[('2019-2020', '2019-2020'), ('2020-2021', '2020-2021'), ('2021-2022', '2022-2023')], max_length=50),
        ),
        migrations.AlterField(
            model_name='planning',
            name='semester',
            field=models.CharField(choices=[('s1', 'Semestre 1'), ('s2', 'Semestre 2')], max_length=20),
        ),
    ]
