# Generated by Django 3.2.13 on 2022-06-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220605_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provide',
            name='range',
            field=models.CharField(choices=[('07h00-9h55', '07h00-9h55'), ('10h05-12h45', '10h05-12h45'), ('13h05-15h55', '13h05-15h55'), ('16h05-18h45', '16h05-18h45'), ('19h05-21h45', '19h05-21h45')], max_length=100),
        ),
    ]
