# Generated by Django 3.2.13 on 2022-05-31 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20220531_1911'),
        ('core', '0003_classroom_provide_teacher_type_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.institution')),
            ],
        ),
        migrations.CreateModel(
            name='PlanningGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=50)),
                ('semestre', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_type',
        ),
        migrations.AddField(
            model_name='classroom',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('TP', 'tp'), ('TD', 'td'), ('Cour', 'cour')], default='cour', max_length=10),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='field',
            name='abr',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='grade',
            name='capacity',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='capacity',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='level',
            name='abr',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.AddField(
            model_name='planninggrade',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grade'),
        ),
        migrations.AddField(
            model_name='planninggrade',
            name='planning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.planning'),
        ),
        migrations.AddField(
            model_name='provide',
            name='planning',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.planning'),
            preserve_default=False,
        ),
    ]
