# Generated by Django 3.2.13 on 2022-05-31 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220531_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.grade'),
            preserve_default=False,
        ),
    ]
